import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fext App</title>
        <meta name="description" content="Generated by create next app and Fable" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Fext</h1>
      <h2>F# and Fable</h2>
      <p>fs(Fable.React.ReactElement) → fable → js(ReactElement) → nextjs → page</p>
      <div><Link href="blog">.fs example</Link></div>
      <p>fsx → FSharp.Formatting → js → nextjs → page</p>
      <div><Link href="literate">.fsx example</Link></div>
    </div>
  )
}
